### ISSUE TITLE
Server crash (on launch)

### ISSUE THREAD

**Issue by admiralaqua** [WildBamaBoy/minecraft-comes-alive#1153]
After updating from the older version to 6.00, my server is crashing on startup. If I remove the mod, it launches fine - I had no trouble with the previous version beyond the obvious issues (crashes, some general glitches) as well. I am using the Forge 14.23.5.2836

This is the crash on the server log:

```
[00:10:28] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Comes Alive (mca)
Caused by: java.lang.NoClassDefFoundError: org/apache/http/client/HttpClient
	at mca.core.MCA.preInit(MCA.java:104) ~[MCA.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge-1.12.2-14.23.5.2836-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge-1.12.2-14.23.5.2836-universal.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge-1.12.2-14.23.5.2836-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.HttpClient
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at mca.core.MCA.preInit(MCA.java:104) ~[MCA.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637) ~[forge-1.12.2-14.23.5.2836-universal.jar:?]
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219) ~[forge-1.12.2-14.23.5.2836-universal.jar:?]
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197) ~[forge-1.12.2-14.23.5.2836-universal.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) ~[minecraft_server.1.12.2.jar:?]
	at com.google.common.eventbus.EventBus.post(EventBus.java:217) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136) ~[LoadController.class:?]
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627) ~[Loader.class:?]
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) ~[FMLServerHandler.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) ~[MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_181]
[00:10:28] [Server thread/WARN] [org.dimdev.utils.ModIdentifier]: Failed to identify sun.reflect.GeneratedMethodAccessor9 (untransformed name: sun.reflect.GeneratedMethodAccessor9)
[00:10:28] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /home/49135/userdata/minecraft-forge/./crash-reports/crash-2019-06-17_00.10.28-server.txt
[00:10:28] [Server thread/INFO] [minecraft/MinecraftServer]: Stopping server
[00:10:28] [Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds
[00:10:28] [Server thread/INFO] [FML]: The state engine was in incorrect state INITIALIZATION and forced into state SERVER_STOPPED. Errors may have been discarded.
```
And this is the full crash report:

```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2019-06-17 00:10:28 UTC
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft Comes Alive (mca)
Caused by: java.lang.NoClassDefFoundError: org/apache/http/client/HttpClient
    at mca.core.MCA.preInit(MCA.java:104)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.http.client.HttpClient
    at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 36 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Linux (amd64) version 4.4.0-142-generic
  Java Version: 1.8.0_181, Oracle Corporation
  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 2625921168 bytes (2504 MB) / 3110862848 bytes (2966 MB) up to 3110862848 bytes (2966 MB)
  JVM Flags: 5 total; -Xms3000M -Xmx3000M -XX:+AggressiveOpts -XX:ParallelGCThreads=4 -XX:+UseConcMarkSweepGC
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2836 93 mods loaded, 93 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                              | Version                  | Source                                               | Signature                                |
       |:----- |:------------------------------- |:------------------------ |:---------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                       | 1.12.2                   | minecraft.jar                                        | None                                     |
       | LCH   | mcp                             | 9.42                     | minecraft.jar                                        | None                                     |
       | LCH   | FML                             | 8.0.99.99                | forge-1.12.2-14.23.5.2836-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                           | 14.23.5.2836             | forge-1.12.2-14.23.5.2836-universal.jar              | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | ivtoolkit                       | 1.3.3-1.12               | minecraft.jar                                        | None                                     |
       | LCH   | foamfixcore                     | 7.7.4                    | minecraft.jar                                        | None                                     |
       | LCH   | aether_legacy                   | 1.4.4                    | aether_legacy-1.12.2-v1.4.4.jar                      | None                                     |
       | LCH   | placebo                         | 1.6.0                    | Placebo-1.12.2-1.6.0.jar                             | None                                     |
       | LCH   | apotheosis                      | 1.10.2                   | Apotheosis-1.12.2-1.10.2.jar                         | None                                     |
       | LCH   | applecore                       | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                         | None                                     |
       | LCH   | mantle                          | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                             | None                                     |
       | LCH   | chisel                          | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                         | None                                     |
       | LCH   | jei                             | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                            | None                                     |
       | LCH   | tconstruct                      | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                     | None                                     |
       | LCH   | conarm                          | 1.2.4                    | conarm-1.12.2-1.2.4.jar                              | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCH   | armoryexpansion                 | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
       | LCH   | armoryexpansion-custommaterials | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
       | LCH   | hammercore                      | 2.0.4.7                  | HammerCore-1.12.2-2.0.4.7.jar                        | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCH   | baubles                         | 1.5.2                    | Baubles-1.12-1.5.2.jar                               | None                                     |
       | LCH   | thaumcraft                      | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                     | None                                     |
       | LCH   | thaumadditions                  | 15r                      | ThaumicAdditions-1.12.2-15r.jar                      | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
       | LCH   | llibrary                        | 1.7.19                   | llibrary-1.7.19-1.12.2.jar                           | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
       | LCH   | iceandfire                      | 1.7.1                    | iceandfire-1.7.1-1.12.2.jar                          | None                                     |
       | LCH   | armoryexpansion-iceandfire      | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
       | LCH   | armoryexpansion-matteroverdrive | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
       | LCH   | quark                           | r1.5-159                 | Quark-r1.5-159.jar                                   | None                                     |
       | LCH   | autoreglib                      | 1.3-30                   | AutoRegLib-1.3-30.jar                                | None                                     |
       | LCH   | bibliocraft                     | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                    | None                                     |
       | LCH   | biomesoplenty                   | 7.0.1.2439               | BiomesOPlenty-1.12.2-7.0.1.2439-universal.jar        | None                                     |
       | LCH   | buildcraftlib                   | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCH   | buildcraftcore                  | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCH   | buildcraftbuilders              | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCH   | buildcrafttransport             | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCH   | buildcraftsilicon               | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCH   | buildcraftenergy                | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCH   | forestry                        | 5.8.1.322                | forestry_1.12.2-5.8.1.322.jar                        | None                                     |
       | LCH   | buildcraftcompat                | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCH   | buildcraftfactory               | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCH   | buildcraftrobotics              | 7.99.24.1                | buildcraft-all-7.99.24.1.jar                         | None                                     |
       | LCH   | chameleon                       | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                             | None                                     |
       | LCH   | morpheus                        | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                          | None                                     |
       | LCH   | comforts                        | 1.4.1.2                  | comforts-1.12.2-1.4.1.2.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | LCH   | dmonsters                       | 1.7                      | Deadly Monsters 1.71.jar                             | None                                     |
       | LCH   | familiarfauna                   | 1.0.11                   | FamiliarFauna-1.12.2-1.0.11.jar                      | None                                     |
       | LCH   | foamfix                         | 0.10.5-1.12.2            | foamfix-0.10.5-1.12.2.jar                            | None                                     |
       | LCH   | forgelin                        | 1.8.2                    | Forgelin-1.8.2.jar                                   | None                                     |
       | LCH   | growthcraft                     | 4.0.4.500                | growthcraft-1.12.2-4.0.4.500.jar                     | None                                     |
       | LCH   | growthcraft_apples              | 4.0.4.500                | growthcraft-1.12.2-4.0.4.500.jar                     | None                                     |
       | LCH   | growthcraft_bamboo              | 4.0.4.500                | growthcraft-1.12.2-4.0.4.500.jar                     | None                                     |
       | LCH   | growthcraft_cellar              | 4.0.4.500                | growthcraft-1.12.2-4.0.4.500.jar                     | None                                     |
       | LCH   | growthcraft_bees                | 4.0.4.500                | growthcraft-1.12.2-4.0.4.500.jar                     | None                                     |
       | LCH   | growthcraft_fishtrap            | 4.0.4.500                | growthcraft-1.12.2-4.0.4.500.jar                     | None                                     |
       | LCH   | growthcraft_grapes              | 4.0.4.500                | growthcraft-1.12.2-4.0.4.500.jar                     | None                                     |
       | LCH   | growthcraft_hops                | 4.0.4.500                | growthcraft-1.12.2-4.0.4.500.jar                     | None                                     |
       | LCH   | growthcraft_milk                | 4.0.4.500                | growthcraft-1.12.2-4.0.4.500.jar                     | None                                     |
       | LCH   | growthcraft_rice                | 4.0.4.500                | growthcraft-1.12.2-4.0.4.500.jar                     | None                                     |
       | LCH   | ichunutil                       | 7.2.1                    | iChunUtil-1.12.2-7.2.1.jar                           | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
       | LCH   | hats                            | 7.0.0                    | Hats-1.12.2-7.0.2.jar                                | None                                     |
       | LCH   | teslacorelib                    | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | industrialforegoing             | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.12-236.jar           | None                                     |
       | LCH   | harvestcraft                    | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zd Surprise for Yogcast.jar | None                                     |
       | LCH   | integrationforegoing            | 1.12.2-1.9               | IntegrationForegoing-1.12.2-1.9.jar                  | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
       | LCH   | inventorytweaks                 | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                             | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | ironchest                       | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.69.845.jar                      | None                                     |
       | LCH   | jeibees                         | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                         | None                                     |
       | LCH   | journeymap                      | 1.12.2-5.5.4             | journeymap-1.12.2-5.5.4.jar                          | None                                     |
       | LCH   | lex                             | 1.0.8                    | LibEx-1.12.2-1.0.8.jar                               | None                                     |
       | LCE   | mca                             | 6.0.0-beta               | MCA-1.12.2-6.0.0-beta-universal.jar                  | None                                     |
       | LC    | mobamputation                   | 7.0.0                    | MobAmputation-1.12.2-7.0.0.jar                       | None                                     |
       | LC    | multimob                        | 1.0.5                    | multimob-1.0.5.jar                                   | None                                     |
       | LC    | nex                             | 2.0.8                    | NetherEx-1.12.2-2.0.8.jar                            | None                                     |
       | LC    | pamscookables                   | 1.1                      | pamscookables-1.1.jar                                | None                                     |
       | LC    | plants2                         | 2.10.7                   | Plants-1.12.2-2.10.7.jar                             | None                                     |
       | LC    | primitivemobs                   | 1.2.3a                   | primitivemobs-1.2.3a.jar                             | None                                     |
       | LC    | projecte                        | 1.12.2-PE1.4.1           | ProjectE-1.12.2-PE1.4.1.jar                          | None                                     |
       | LC    | projecteintegration             | 1.12.2                   | ProjectEIntegration-1.12.2-2.2.13.jar                | 342c9251777bda1ef9b9f1cb1387c2bd4d06cd78 |
       | LC    | projectex                       | 1.2.0.36                 | ProjectEX-1.2.0.36.jar                               | None                                     |
       | LC    | pvj                             | 1.6.3                    | ProjectVibrantJourneys-1.12.2-1.6.3.jar              | None                                     |
       | LC    | railcraft                       | 12.0.0                   | railcraft-12.0.0.jar                                 | a0c255ac501b2749537d5824bb0f0588bf0320fa |
       | LC    | reccomplex                      | 1.4.8.2                  | RecurrentComplex-1.4.8.2.jar                         | None                                     |
       | LC    | refinedstorage                  | 1.6.14                   | refinedstorage-1.6.14.jar                            | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LC    | roguelike                       | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                   | None                                     |
       | LC    | solcarrot                       | 1.12.2-1.7               | solcarrot-1.12.2-1.7.jar                             | None                                     |
       | LC    | sophisticatedwolves             | 3.13.8                   | SophisticatedWolves-1.12.2-3.13.8.jar                | None                                     |
       | LC    | soulshardstow                   | 1.12-2.7.6-56            | SoulShards-TOW-1.12-2.7.6-56.jar                     | None                                     |
       | LC    | storagedrawers                  | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                      | None                                     |
       | LC    | thaumicequivalence              | 1.12.2-1.0.5             | ThaumicEquivalence-1.12.2-1.0.5.jar                  | None                                     |
       | LC    | tinkersjei                      | 1.2                      | tinkersjei-1.2.jar                                   | None                                     |
       | LC    | ultimate_unicorn_mod            | 1.5.16                   | ultimate_unicorn_mod-1.12.2-1.5.16.jar               | None                                     |
       | LC    | vanillafix                      | 1.0.10-SNAPSHOT          | VanillaFix-1.0.10-99.jar                             | None                                     |
       | LC    | armoryexpansion-conarm          | 1.3.1                    | armoryexpansion-1.3.1.jar                            | None                                     |
       | LC    | teslacorelib_registries         | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                     | None                                     |
       | LC    | tinkersurvival                  | 1.2.2.1                  | TinkerSurvival-1.12.2-1.2.2.1.jar                    | 9cd6bcf5f667bff0b7825080f467db605192243c |
  Loaded coremods (and transformers): llibrary (llibrary-core-1.0.11-1.12.2.jar)
                                        net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
                                        net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      HCASM (HammerCore-1.12.2-2.0.4.7.jar)
                                        com.zeitheron.hammercore.asm.HammerCoreTransformer
                                      Quark Plugin (Quark-r1.5-159.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      IvToolkit (IvToolkit-1.3.3-1.12.jar)
                                        
                                      ForgelinPlugin (Forgelin-1.8.2.jar)
                                        
                                      ApotheosisCore (Apotheosis-1.12.2-1.10.2.jar)
                                        shadows.ApotheosisTransformer
                                      Born in a Barn (Born In A Barn V1.8-1.12-1.1.jar)
                                        com.chocohead.biab.BornInABarn
                                      CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
  Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
                           OreDictionary Info: Registered 343 names; 736 stacks.
                           Pastebin Connection: Okay.
                           Dependent Mods:
                               -Thaumic Additions: Reconstructed (thaumadditions) @15r
  Suspected Mods: Minecraft Comes Alive (mca)
  Profiler Position: N/A (disabled)
  Is Modded: Definitely; Server brand changed to 'fml,forge'
  Type: Dedicated Server (map_server.txt)
```
All help would be appreciated - we were really looking forward to playing on the new update. 

Thank you! :)

**Comment by admiralaqua** [comment]
Nevermind, I just figured out there was a hotfix.
